CREATE TABLE IF NOT EXISTS public.qr_templates (
  id         BIGSERIAL PRIMARY KEY,
  name       TEXT NOT NULL,
  width_mm   FLOAT NOT NULL DEFAULT 85,
  height_mm  FLOAT NOT NULL DEFAULT 54,
  elements   JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
